FROM node:22 AS builder
ARG API_URL
ARG WS_URL

ENV API_URL=$API_URL
ENV WS_URL=$WS_URL

RUN mkdir -p /home/tapiz

COPY ./ /home/tapiz

WORKDIR /home/tapiz

RUN npm ci
RUN npm run config
RUN npx nx run web:build:production
RUN npm prune --production
RUN rm -rf apps libs resources

FROM nginx:1.25.0-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /home/tapiz/dist/apps/web /usr/share/nginx/html
RUN touch /var/run/nginx.pid
RUN chown -R nginx:nginx /var/run/nginx.pid /usr/share/nginx/html /var/cache/nginx /var/log/nginx /etc/nginx/conf.d
USER nginx
