FROM node:22 AS builder

RUN mkdir -p /home/tapiz

COPY ./ /home/tapiz

WORKDIR /home/tapiz

RUN npm ci
RUN npx nx run web:build:production
RUN npm prune --production
RUN rm -rf apps libs resources

FROM nginx:1.25.0-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /home/tapiz/dist/apps/web /usr/share/nginx/html
COPY --from=builder /home/tapiz/generate-config.sh /docker-entrypoint.d/40-generate-config.sh

RUN touch /var/run/nginx.pid
RUN chown -R nginx:nginx /var/run/nginx.pid /usr/share/nginx/html /var/cache/nginx /var/log/nginx /etc/nginx/conf.d
RUN chmod +x /docker-entrypoint.d/40-generate-config.sh

USER nginx
