FROM node:24-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /home/tapiz

COPY ./ /home/tapiz

FROM base AS builder
ARG API_URL
ARG WS_URL

ENV API_URL=$API_URL
ENV WS_URL=$WS_URL

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --ignore-scripts
RUN pnpm run config
RUN pnpm nx run web:build:production

FROM nginx:1.25.0-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /home/tapiz/dist/apps/web /usr/share/nginx/html
RUN touch /var/run/nginx.pid
RUN chown -R nginx:nginx /var/run/nginx.pid /usr/share/nginx/html /var/cache/nginx /var/log/nginx /etc/nginx/conf.d
USER nginx
