services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT_HOST}:5432'

  api:
    restart: always
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/home/tapiz/uploads

  web:
    restart: always
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.web
      args:
        - API_URL=${API_URL}
        - WS_URL=${WS_URL}
    depends_on:
      - api
    ports:
      - '${FRONTEND_PORT}:80'
    env_file:
      - .env

volumes:
  pgdata:
