version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${DB_PORT_HOST}:${DB_PORT}'

  api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.api
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./firebase:/home/team-up/firebase

  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.web
    depends_on:
      - api
    ports:
      - '${WEB_PORT}:80'
    env_file:
      - .env
    volumes:
      - ${FIREBASE_CONFIG}:/usr/share/nginx/html/assets/firebase.json

volumes:
  pgdata:
