FROM node:18

RUN mkdir -p /home/team-up

COPY ./ /home/team-up

WORKDIR /home/team-up

RUN npm ci
RUN npx nx run api:build:production
RUN npm prune --production
RUN rm -rf apps libs resources

EXPOSE 8000

CMD ["node", "dist/apps/api/main.js"]
