import { registerNode } from './register-node';
import { ESTIMATION_BOARD_CONFIG } from './modules/board/components/estimation-board';
import { TEXT_CONFIG } from './modules/board/components/text';
import { IMAGE_CONFIG } from './modules/board/components/image';
import { VECTOR_CONFIG } from './modules/board/components/vector';
import { PANEL_CONFIG } from './modules/board/components/panel';
import { POLL_BOARD_CONFIG } from './modules/board/components/poll-board';
import { PERSONAL_TOKEN_CONFIG } from './modules/board/components/token/register';
import { NOTE_CONFIG } from './modules/board/components/note';
import { GROUP_CONFIG } from './modules/board/components/group';
import { ARROW_NODE_CONFIG } from './modules/board/components/arrows/arrow-node/register';

registerNode('token', PERSONAL_TOKEN_CONFIG);
registerNode('estimation', ESTIMATION_BOARD_CONFIG);
registerNode('text', TEXT_CONFIG);
registerNode('image', IMAGE_CONFIG);
registerNode('vector', VECTOR_CONFIG);
registerNode('panel', PANEL_CONFIG);
registerNode('poll', POLL_BOARD_CONFIG);
registerNode('note', NOTE_CONFIG);
registerNode('group', GROUP_CONFIG);
registerNode('arrow', ARROW_NODE_CONFIG);
