version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    ports:
      - '${DB_PORT_HOST}:${DB_PORT_CONTAINER}'
