const prefix = '[Board]';

export const BoardActions = {
  joinBoard: `${prefix} join board`,
  setZoom: `${prefix} set zoom`,
  setUserView: `${prefix} set user view`,
  addNode: `${prefix} add node`,
  removeNode: `${prefix} remove node`,
  patchNode: `${prefix} patch node`,
  setImagePosition: `${prefix} set image position`,

  setMoveEnabled: `${prefix} set move enabled`,
  moveCursor: `${prefix} move cursor`,
  editImage: `${prefix} edit image`,
  wsSetState: `${prefix} ws set state`,
  newPath: `${prefix} new path`,
  setUserId: `${prefix} set user id`,

  setInitZone: `${prefix} set init zone`,
  setFocusId: `${prefix} set focus id`,
  setVisible: `${prefix} set visible`,
  setZone: `${prefix} set zone`,
  zoneToGroup: `${prefix} zone to group`,
  zoneToPanel: `${prefix} zone to panel`,
  initDragNode: `${prefix} init drag node`,
  endDragNode: `${prefix} end drag node`,
  undo: `${prefix} undo`,
  redo: `${prefix} redo`,
  toggleUserHighlight: `${prefix} toggle user highlight`,

  setBoardName: `${prefix} set board name`,
  setPopupOpen: `${prefix} set popup open`,
  createBoard: `${prefix} create board`,
  fetchBoards: `${prefix} fetch boards`,
  fetchBoardsSuccess: `${prefix} fetch boards success`,
  initBoard: `${prefix} init board`,
  closeBoard: `${prefix} close board`,
  textToolbarClick: `${prefix} text toolbar click`,
  fetchBoardSuccess: `${prefix}[api] fetch board success`,
  readyToVote: `${prefix} ready to vote`,
  removeBoard: `${prefix} remove board`,

  newImage: `${prefix}[local] new image`,
  removeImage: `${prefix}[local] remove image`,
  newNote: `${prefix}[local] new note`,
  removeNote: `${prefix}[local] remove note`,
  newText: `${prefix}[local] new text`,
  removeText: `${prefix}[local] remove text`,

  changeCanvasMode: `${prefix} change canvas mode`,
  setCanvasActive: `${prefix} set canvas active`,
  canvasObjectAdded: `${prefix} canvas object added`,
  canvasObjectModified: `${prefix} canvas object modified`,
};
