const prefix = '[Board]';

export const BoardActions = {
  joinRoom: `${prefix} join room`,
  setZoom: `${prefix} set zoom`,
  setUserView: `${prefix} set user view`,
  addNode: `${prefix} add node`,
  removeNode: `${prefix} remove node`,
  patchNode: `${prefix} patch node`,
  setImagePosition: `${prefix} set image position`,

  setDrawEnabled: `${prefix} set draw enabled`,
  setMoveEnabled: `${prefix} set move enabled`,
  moveCursor: `${prefix} move cursor`,
  editImage: `${prefix} edit image`,
  wsSetState: `${prefix} ws set state`,
  newPath: `${prefix} new path`,
  setUserId: `${prefix} set user id`,
  changeCanvasMode: `${prefix} change canvas mode`,
  setInitZone: `${prefix} set init zone`,
  changeBrushSize: `${prefix} change brush size`,
  changeBrushColor: `${prefix} change brush color`,
  setFocusId: `${prefix} set focus id`,
  setVisible: `${prefix} set visible`,
  setZone: `${prefix} set zone`,
  zoneToGroup: `${prefix} zone to group`,
  zoneToPanel: `${prefix} zone to panel`,
  initDragNode: `${prefix} init drag node`,
  endDragNode: `${prefix} end drag node`,
  undo: `${prefix} undo`,
  redo: `${prefix} redo`,
  toggleUserHighlight: `${prefix} toggle user highlight`,
  setCanvasActive: `${prefix} set canvas active`,
  canvasObjectAdded: `${prefix} canvas object added`,
  canvasObjectModified: `${prefix} canvas object modified`,
  setBoardName: `${prefix} set board name`,
  setPopupOpen: `${prefix} set popup open`,
  createBoard: `${prefix} create board`,
  fetchBoards: `${prefix} fetch boards`,
  fetchBoardsSuccess: `${prefix} fetch boards success`,
  initBoard: `${prefix} init board`,
  closeBoard: `${prefix} close board`,
  textToolbarClick: `${prefix} text toolbar click`,
  fetchRoomSuccess: `${prefix}[api] fetch room success`,
  readyToVote: `${prefix} ready to vote`,
  removeBoard: `${prefix} remove board`,

  newImage: `${prefix}[local] new image`,
  removeImage: `${prefix}[local] remove image`,
  newNote: `${prefix}[local] new note`,
  removeNote: `${prefix}[local] remove note`,
  newText: `${prefix}[local] new text`,
  removeText: `${prefix}[local] remove text`,
};
