FROM node:22

RUN mkdir -p /home/tapiz

COPY ./ /home/tapiz

WORKDIR /home/tapiz

RUN npm ci
RUN npx nx run api:build:production
RUN npm prune --production
RUN rm -rf apps libs resources

CMD ["node", "dist/apps/api/main.js"]
